ReklamoTv.Web/ViewModels/ReferanceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace ReklamoTv.Web.ViewModels
{
    public class ReferanceViewModel
    {
        public int ReferanceId { get; set; }
        [DisplayName("Başlık")]
        public string ReferanceTitle { get; set; }
        [DisplayName("Logo")]
        public string Referanceİmage { get; set; }
        [DisplayName("Açıklama")]
        public string Description { get; set; }
    }
}

ReklamoTv.Web/Controllers/ReferanceController.cs
using AutoMapper;
using ReklamoTv.Model;
using ReklamoTv.Service;
using ReklamoTv.Web.Models;
using ReklamoTv.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReklamoTv.Web.Controllers
{
    public class ReferanceController:Controller
    {
        private readonly IReferanceService referanceService;
        protected readonly string UploadPath;

        public ReferanceController(IReferanceService referanceService)
        {
            this.referanceService = referanceService;
            this.UploadPath = ConfigurationManager.AppSettings["UploadPath"];
        }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ReferanceFormViewModel referanceForm, System.Web.HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {

                var referance= Mapper.Map<ReferanceFormViewModel, Referance>(referanceForm);
                if (upload != null)
                {

                            string filePath = Path.GetFileName(upload.FileName);

                            var uploadAddress = Path.Combine(Server.MapPath("~/ReferanceFile"), filePath);
                            upload.SaveAs(uploadAddress);
                            referance.Referanceİmage = upload.FileName;
      
                }
                referanceService.CreateReferance(referance);
                referanceService.SaveReferance();
                return RedirectToAction("Index");
            }
            return View(referanceForm);
        }
        public ActionResult AjaxHandler(jQueryDataTableParamModel param)
        {
            string sSearch = "";
            if (param.sSearch != null) sSearch = param.sSearch;
            var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);
            var sortDirection = Request["sSortDir_0"]; // asc or desc
            int iTotalRecords;
            int iTotalDisplayRecords;
            var displayedReferances = referanceService.Search(sSearch, sortColumnIndex, sortDirection, param.iDisplayStart, param.iDisplayLength, out iTotalRecords, out iTotalDisplayRecords);

            var result = from r in displayedReferances
                         select new[] { r.ReferanceId.ToString(), r.Description, r.ReferanceTitle,r.Referanceİmage, string.Empty };
            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = iTotalRecords,
                iTotalDisplayRecords = iTotalDisplayRecords,
                aaData = result.ToList()
            },
                JsonRequestBehavior.AllowGet);

        }


        public ActionResult Edit(int? id)
        {
            if (id.HasValue)
            {
                var referance = referanceService.GetReferance(id.Value);
                if (referance != null)
                {
                    var referanceViewModel = Mapper.Map<Referance, ReferanceViewModel>(referance);
                    return View(referanceViewModel);
                }

            }
            return HttpNotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ReferanceFormViewModel referanceForm)
        {
            if (ModelState.IsValid)
            {
                var referance = Mapper.Map<ReferanceFormViewModel, Referance>(referanceForm);
                referanceService.UpdateReferance(referance);
                referanceService.SaveReferance();
                return RedirectToAction("Index");
            }
            return View(referanceForm);
        }
        public ActionResult Delete(int? id)
        {
            if (id.HasValue)
            {
                var referance = referanceService.GetReferance(id.Value);
                if (referance != null)
                {
                    referanceService.DeleteReferance(referance);
                    referanceService.SaveReferance();
                    return RedirectToAction("Index");
                }

            }
            return HttpNotFound();
        }


    }
}

ReklamoTv.Web/Views/Referance/Create.cshtml
@model ReklamoTv.Web.ViewModels.ReferanceFormViewModel
@{
    ViewBag.Title = "Referans güncelleme";
}



<link href="assest/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="assest/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<br />
<div class="page-bar">
    <ul class="page-breadcrumb">

        <li>
            <span>Referans</span>
        </li>
    </ul>

</div>
<br />
<div class="row">
    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <h1 class="page-title">
                    Referans
                </h1>

            </div>
            <div class="row">
                <div class="col-md-12">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                </div>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="portlet-body form">
                    <form role="form">
                        <div class="form-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ReferanceTitle)
                                @Html.EditorFor(model => model.ReferanceTitle, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus" } })
                                @Html.ValidationMessageFor(model => model.ReferanceTitle, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Description)
                            @Html.TextAreaFor(model => model.Description, new { @tabindex = "4", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Description, " ", new { @class = "text-danger" })

                        </div>

                        <div class="form-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Referanceİmage)
                                @Html.HiddenFor(model => model.Referanceİmage)

                               
                                <form id="form1" runat="server">
                                    <input type='file' id="FileName" name="upload" />
                                    <img id="ReferanceId" src="#" alt="your image" style="max-width: 200px; max-height: 150px;" />
                                </form>
                            </div>
                        </div>
                        

                        <div class="form-actions">
                            <button type="submit" class="btn blue">Ekle</button>
                            <button type="button" class="btn default" onclick="window.location='@Url.Action("Index","Referance")';">İptal</button>
                        </div>
                    </form>
                </div>
            }
        </div>
    </div>

</div>
<!-- END SAMPLE FORM PORTLET-->
<!-- BEGIN SAMPLE FORM PORTLET-->

@section Scripts {
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#ReferanceId').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#FileName").change(function () {
            readURL(this);
        });
    </script>

    @Scripts.Render("~/bundles/jqueryval")
}

ReklamoTv.Web/Views/Referance/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

ReklamoTv.Web/Views/Referance/Edit.cshtml
@model ReklamoTv.Web.ViewModels.ReferanceViewModel
@{
    ViewBag.Title = "Düzenle";
}


<link href="assest/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="assest/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<br />
<div class="page-bar">


</div>
<br />
<div class="row">
    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light bordered" style="
             width 442px;">
            <div class="portlet-title">
                <h1 class="page-title">Düzenle</h1>

            </div>
            <div class="row">
                <div class="col-md-12">

                </div>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="portlet-body form">
                    <form role="form">
                        <div class="form-group">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.ReferanceId)
                            <div class="form-body">

                                @Html.LabelFor(model => model.Referanceİmage)
                                @Html.EditorFor(model => model.Referanceİmage, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner" } })
                                @Html.ValidationMessageFor(model => model.Referanceİmage, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">

                                @Html.LabelFor(model => model.ReferanceTitle)
                                @Html.EditorFor(model => model.ReferanceTitle, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner" } })
                                @Html.ValidationMessageFor(model => model.ReferanceTitle, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">

                                @Html.LabelFor(model => model.Description)
                                @Html.TextAreaFor(model => model.Description, new { @tabindex = "4", @class = "form-control spinner" })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>



                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn blue">Kaydet</button>
                            <button type="button" class="btn default" onclick="window.location='@Url.Action("Index","Referance")';">İptal</button>
                        </div>
                    </form>
                </div>
            }
        </div>
    </div>

</div>
<!-- END SAMPLE FORM PORTLET-->
<!-- BEGIN SAMPLE FORM PORTLET-->
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReklamoTv.Web/Views/Referance/Index.cshtml
@{
    ViewBag.Title = "Referans";
}

<link href="assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<br />
<div class="page-bar">

</div>
<br />
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <h1 class="page-title">
                    Referans
                </h1>
            </div>

            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="btn-group">

                                <a href="/Referance/Create" id="sample_editable_1_new" class=" btn sbold green">
                                    Referans
                                    <i class="fa fa-plus"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover table-checkable order-column" id="allReferanceTable">
                    <thead>
                        <tr>
                            <th>
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input type="checkbox" class="group-checkable" data-set="#allReferanceTable .checkboxes" />
                                    <span></span>
                                </label>
                            </th>
                            <th>Baslik</th>
                            <th>Aciklama</th>
                            <th>Logo</th>
                            <th>Eylemler</th>
                        </tr>
                    </thead>

                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>
@section footer {
    <script src="assets/global/scripts/datatable.js" type="text/javascript"></script>
    <script src="assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
    <script src="assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
    <script src="~/Scripts/pages/referance-index.js"></script>
    <script>
        $(document).ready(function () {
            initTable1();
        });
    </script>
}