ReklamoTv.Web/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ReklamoTv.Web.ViewModels
{
    public class ContactViewModel
    {
        public int ContactId { get; set; }
        [DisplayName("Adres")]
        public string ContactAdress { get; set; }
        [DisplayName("Telefon")]
        public string ContactPhone { get; set; }
        [Required(ErrorMessage = "Lütfen E-mail adresi giriniz")]
        [DisplayName("E-mail 1")]
        public string FirstEMail { get; set; }
        [DisplayName("E-mail 2")]
        public string SecondEMail { get; set; }
        [DisplayName("Skype")]
        public string SkypeAdress { get; set; }
        [DisplayName("Facebook")]
        public string FacebookAdress { get; set; }
        [DisplayName("Twitter")]
        public string TwitterAdress { get; set; }
        [DisplayName("Linked")]
        public string LinkedAdress { get; set; }
        [DisplayName("Google")]
        public string GoogleAdress { get; set; }
        [DisplayName("Enlem")]
        public string Latitude { get; set; }
        [DisplayName("Boylam")]
        public string Longtitude { get; set; }

    }
}

ReklamoTv.Web/Controllers/ContactController.cs
using AutoMapper;
using ReklamoTv.Model;
using ReklamoTv.Service;
using ReklamoTv.Web.Models;
using ReklamoTv.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReklamoTv.Web.Controllers
{
    public class ContactController:Controller
    {

        private readonly IContactService contactService;

        public ContactController(IContactService contactService)
        {
            this.contactService = contactService;
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ContactFormViewModel contactForm)
        {
            if (ModelState.IsValid)
            {
               
                var contact = Mapper.Map<ContactFormViewModel, Contact>(contactForm);

                contactService.CreateContact(contact);
                contactService.SaveContact();
                return RedirectToAction("Index");
            }
            return View(contactForm);
        }
        public ActionResult AjaxHandler(jQueryDataTableParamModel param)
        {
            string sSearch = "";
            if (param.sSearch != null) sSearch = param.sSearch;
            var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);
            var sortDirection = Request["sSortDir_0"]; // asc or desc
            int iTotalRecords;
            int iTotalDisplayRecords;
            var displayedContacts = contactService.Search(sSearch, sortColumnIndex, sortDirection, param.iDisplayStart, param.iDisplayLength, out iTotalRecords, out iTotalDisplayRecords);

            var result = from c in displayedContacts
                         select new[] { c.ContactId.ToString(), c.ContactAdress,c.ContactPhone,c.FirstEMail,string.Empty };
            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = iTotalRecords,
                iTotalDisplayRecords = iTotalDisplayRecords,
                aaData = result.ToList()
            },
                JsonRequestBehavior.AllowGet);

        }


        public ActionResult Edit(int ? id)
        {
            if (id.HasValue)
            {
                var contact = contactService.GetContact(id.Value);
                if (contact != null)
                {
                    var contactViewModel = Mapper.Map<Contact, ContactViewModel>(contact);
                    return View(contactViewModel);
                }

            }
            return HttpNotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ContactFormViewModel contactForm)
        {
            if (ModelState.IsValid)
            {
                var contact = Mapper.Map<ContactFormViewModel,Contact>(contactForm);
                contactService.UpdateContact(contact);
                contactService.SaveContact();
                return RedirectToAction("Index");
            }
            return View(contactForm);
        }
        public ActionResult Delete( int? id)
        {
            if (id.HasValue)
            {
                var contact =contactService.GetContact(id.Value);
                if (contact != null)
                {
                   contactService.DeleteContact(contact);
                    contactService.SaveContact();
                    return RedirectToAction("Index");
                }

            }
            return HttpNotFound();
        }


    }
}

ReklamoTv.Web/Views/Contact/Create.cshtml
@model ReklamoTv.Web.ViewModels.ContactFormViewModel
@{
    ViewBag.Title = "İletişim Güncelle";
}

<link href="assest/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="assest/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<br />
<div class="page-bar">
    <ul class="page-breadcrumb">

        <li>
            <span>İletişim</span>
        </li>
    </ul>

</div>
<br />
<div class="row">
    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <h1 class="page-title">
                    İletişim Güncelle
                </h1>

            </div>
            <div class="row">
                <div class="col-md-12">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                </div>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="portlet-body form">
                    <form role="form">
                        <div class="form-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ContactAdress)
                                @Html.EditorFor(model => model.ContactAdress, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus" } })
                                @Html.ValidationMessageFor(model => model.ContactAdress, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ContactPhone)
                                @Html.EditorFor(model => model.ContactPhone, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus" } })
                                @Html.ValidationMessageFor(model => model.ContactPhone, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.FirstEMail)
                            @Html.TextAreaFor(model => model.FirstEMail, new { @tabindex = "4", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.FirstEMail, " ", new { @class = "text-danger" })
                        </div>
                        <div class="form-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.SecondEMail)
                                @Html.TextAreaFor(model => model.SecondEMail, new { @tabindex = "4", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.SecondEMail, " ", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.SkypeAdress)
                                @Html.TextAreaFor(model => model.SkypeAdress, new { @tabindex = "4", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.SkypeAdress, " ", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.FacebookAdress)
                                    @Html.TextAreaFor(model => model.SkypeAdress, new { @tabindex = "4", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.SkypeAdress, " ", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-body">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.TwitterAdress)
                                    @Html.TextAreaFor(model => model.TwitterAdress, new { @tabindex = "4", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.TwitterAdress, " ", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-body">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.LinkedAdress)
                                    @Html.TextAreaFor(model => model.LinkedAdress, new { @tabindex = "4", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.LinkedAdress, " ", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-body">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.GoogleAdress)
                                    @Html.TextAreaFor(model => model.GoogleAdress, new { @tabindex = "4", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.GoogleAdress, " ", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-body">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Latitude)
                                    @Html.TextAreaFor(model => model.Latitude, new { @tabindex = "4", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Latitude, " ", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Longtitude)
                                @Html.TextAreaFor(model => model.Longtitude, new { @tabindex = "4", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Longtitude, " ", new { @class = "text-danger" })
                            </div>
                        </div>

                            <div class="form-actions">
                                <button type="submit" class="btn blue">Ekle</button>
                                <button type="button" class="btn default" onclick="window.location='@Url.Action("Index","Contact")';">İptal</button>
                            </div>
                    </form>
                </div>
            }
        </div>
    </div>

</div>
<!-- END SAMPLE FORM PORTLET-->
<!-- BEGIN SAMPLE FORM PORTLET-->

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReklamoTv.Web/Views/Contact/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

ReklamoTv.Web/Views/Contact/Edit.cshtml
@model ReklamoTv.Web.ViewModels.ContactViewModel
@{
    ViewBag.Title = "Düzenle";
}
<link href="assest/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="assest/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<br />
<div class="page-bar">


</div>
<br />

<div class="row">
    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light bordered" style=
              width 442px;">
            <div class="portlet-title">
                <h1 class="page-title">Düzenle</h1>

            </div>
            <div class="row">
                <div class="col-md-12">

                </div>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="portlet-body form">
                    <form role="form">
                        <div class="form-group">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.ContactId)
                            <div class="form-body">

                                @Html.LabelFor(model => model.ContactAdress)
                                @Html.EditorFor(model => model.ContactAdress, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner" } })
                                @Html.ValidationMessageFor(model => model.ContactAdress, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-body">

                                @Html.LabelFor(model => model.ContactPhone)
                                @Html.EditorFor(model => model.ContactPhone, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner" } })
                                @Html.ValidationMessageFor(model => model.ContactPhone, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">

                                @Html.LabelFor(model => model.FirstEMail)
                                @Html.EditorFor(model => model.FirstEMail, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner" } })
                                @Html.ValidationMessageFor(model => model.FirstEMail, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">

                                @Html.LabelFor(model => model.SecondEMail)
                                @Html.EditorFor(model => model.SecondEMail, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner" } })
                                @Html.ValidationMessageFor(model => model.SecondEMail, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-body">

                                @Html.LabelFor(model => model.FacebookAdress)
                                @Html.EditorFor(model => model.FacebookAdress, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner" } })
                                @Html.ValidationMessageFor(model => model.FacebookAdress, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">

                                @Html.LabelFor(model => model.LinkedAdress)
                                @Html.EditorFor(model => model.LinkedAdress, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner" } })
                                @Html.ValidationMessageFor(model => model.LinkedAdress, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">

                                @Html.LabelFor(model => model.SkypeAdress)
                                @Html.EditorFor(model => model.SkypeAdress, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner" } })
                                @Html.ValidationMessageFor(model => model.SkypeAdress, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">

                                @Html.LabelFor(model => model.TwitterAdress)
                                @Html.EditorFor(model => model.TwitterAdress, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner" } })
                                @Html.ValidationMessageFor(model => model.TwitterAdress, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">

                                @Html.LabelFor(model => model.GoogleAdress)
                                @Html.EditorFor(model => model.GoogleAdress, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner" } })
                                @Html.ValidationMessageFor(model => model.GoogleAdress, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">

                                @Html.LabelFor(model => model.Latitude)
                                @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner" } })
                                @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">

                                @Html.LabelFor(model => model.Longtitude)
                                @Html.EditorFor(model => model.Longtitude, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner" } })
                                @Html.ValidationMessageFor(model => model.Longtitude, "", new { @class = "text-danger" })
                            </div>

                        @*</div>*@
                        <div class="form-actions">
                            <button type="submit" class="btn blue">Kaydet</button>
                            <button type="button" class="btn default" onclick="window.location='@Url.Action("Index","Contact")';">İptal</button>
                        </div>
                    </form>
                </div>
            }
        </div>
    </div>

</div>
<!-- END SAMPLE FORM PORTLET-->
<!-- BEGIN SAMPLE FORM PORTLET-->
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")

    }

ReklamoTv.Web/Views/Contact/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<link href="assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<br />
<div class="page-bar">

</div>
<br />
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <h1 class="page-title">
                  İletişim
                </h1>
            </div>

            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="btn-group">
                                <a href="/Contact/Create" id="sample_editable_1_new" class=" btn sbold green">
                                   İletişim
                                    <i class="fa fa-plus"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover table-checkable order-column" id="allContactTable">
                    <thead>
                        <tr>
                            <th>
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input type="checkbox" class="group-checkable" data-set="#allContactTable .checkboxes" />
                                    <span></span>
                                </label>
                            </th>

                            <th>Adres</th>
                            <th>Telefon</th>
                            <th>E-mail 1</th>
                            <th>Eylemler</th>
                            
                        </tr>
                    </thead>

                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>
@section footer {
    <script src="assets/global/scripts/datatable.js" type="text/javascript"></script>
    <script src="assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
    <script src="assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
    <script src="~/Scripts/pages/contact-index.js"></script>
    <script>
        $(document).ready(function () {
            initTable1();
        });
    </script>
}