ReklamoTv.Web/ViewModels/AboutUsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ReklamoTv.Web.ViewModels
{
    public class AboutUsViewModel
    {
        public int AboutId { get; set; }
        [DisplayName("Açıklama")]
        [Required(ErrorMessage ="Lütfen açıklama giriniz")]
        public string Description { get; set; }
        [DisplayName("Başlık")]
        [Required(ErrorMessage = "Lütfen başlık giriniz")]
        public string AboutTitle { get; set; }
    }
}

ReklamoTv.Web/Controllers/AboutUsController.cs
using AutoMapper;
using ReklamoTv.Model;
using ReklamoTv.Service;
using ReklamoTv.Web.Models;
using ReklamoTv.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReklamoTv.Web.Controllers
{
    public class AboutUsController:Controller
    {
        private readonly IAboutUsService aboutusService;
           
        public AboutUsController(IAboutUsService aboutusService)
        {
            this.aboutusService = aboutusService;
        }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AboutUsFormViewModel aboutusForm)
        {
            if (ModelState.IsValid)
            {
                
                var aboutus = Mapper.Map<AboutUsFormViewModel, AboutUs>(aboutusForm);

                aboutusService.CreateAboutUs(aboutus);
                aboutusService.SaveAboutUs();
                return RedirectToAction("Index");
            }
            return View(aboutusForm);
        }
       


        public ActionResult Edit(int ? id)
        {
            if (id.HasValue)
            {
                var abotus = aboutusService.GetAboutUs(id.Value);
                if (abotus != null)
                {
                    var aboutusViewModel = Mapper.Map<AboutUs, AboutUsViewModel>(abotus);
                    return View(aboutusViewModel);
                }

            }
            return HttpNotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AboutUsFormViewModel aboutusForm)
        {
            if (ModelState.IsValid)
            {
                var aboutus = Mapper.Map<AboutUsFormViewModel, AboutUs>(aboutusForm);
                aboutusService.UpdateAboutUs(aboutus);
                aboutusService.SaveAboutUs();
                return RedirectToAction("Index");
            }
            return View(aboutusForm);
        }
        public ActionResult Delete(int? id)
        {
            if (id.HasValue)
            {
                var aboutus =aboutusService.GetAboutUs(id.Value);
                if (aboutus != null)
                {
                    aboutusService.DeleteAboutUs(aboutus);
                    aboutusService.SaveAboutUs();
                    return RedirectToAction("Index");
                }

            }
            return HttpNotFound();
        }


    }
}

ReklamoTv.Web/Views/AboutUs/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

ReklamoTv.Web/Views/AboutUs/Edit.cshtml
@model ReklamoTv.Web.ViewModels.AboutUsViewModel
@{
    ViewBag.Title = " Düzenle ";
}
<link href="assest/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="assest/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<br />
<div class="page-bar">

</div>
<br />
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light bordered" style="width 422px;">
            <div class="popover-title">
                <h1 class="page-title"> Düzenle</h1>

            </div>
            <div class="row">
                <div class="col-lg-12">

                </div>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="portlet-body form">
                        <form role="form">
                            <div class="form-group">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.AboutId)
                                <div class="form-body">
                                    @Html.LabelFor(model => model.AboutTitle)
                                    @Html.EditorFor(model => model.AboutTitle, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus" } })
                                    @Html.ValidationMessageFor(model => model.AboutTitle, "", new { @class = "text-danger" })
                                </div>
                            
                                <div class="form-body">
                                    @Html.LabelFor(model => model.Description)
                                   <br/>
                                    @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    @*<textarea  metin  cols="10 "rows="5"> </textarea> <br/>*@
                                </div>
                                
                            </div>

                            <div class="form-actions">
                                <button type="submit" class="btn blue">Ekle</button>
                                <button type="button" class="btn default" onclick="window.location='@Url.Action("Index","AboutUs")';">İptal</button>
                            </div>
                        </form>
                    </div>
                }

            </div>
        </div>

    </div>

</div>
<!-- END SAMPLE FORM PORTLET-->
<!-- BEGIN SAMPLE FORM PORTLET-->
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

ReklamoTv.Web/Views/AboutUs/Index.cshtml
@{
    ViewBag.Title = "Hakkında";
}
Reklam mecraları konusunda uzman şirketimiz 2003 yılında Reklamotif adıyla kurulmuştur. Temel hizmetlerimiz iç mekan ve diş mekan reklamcılığı olmakla beraber, son yıllardaki dijital gelişmeler insan hayatında ki bir çok durumu değiştirdiği gibi ticari faaliyet yürüten kurumların vizyon ve misyonlarında da önemli etkiler meydana getirdi. Bu gelişmeler uzman ekibimiz tarafından iyi bir şekilde analiz edilerek ürün yelpazemize iç mekan LCD reklam oynatıcılarını da ekledik.

ReklamoTV; tüm bu araştırmaların ve uzun yıllar kazanılan tecrübenin teknoloji ile buluştuğu yeni yüzü olmuştur. Günümüzde reklamcılığı klasik yöntemlerden kurtararak arge, programlama ve yazılım çalışmalarıyla bilimsel bir çizgiye yaklaştırmıştır. ReklamoTV ekranlarına sahip olduğunuz andan itibaren her nerede olursanız olun artık ekranlarınızı yönetmek bir tik uzağınızda. Dijital Ekran programıyla ekranlara dilediğiniz içeriği saniyeler içerisinde gönderin ve dilediğiniz içeriği de kaldırın.

Türkiye genelinde ReklamoTV ailesine katılan reklam firmaları ürün, hizmet ve kalitemizin en güçlü referansıdır. Vermekte olduğumuz bayilikler yanında bireysel ve kurumsal işletmeciler içinde ekran satışlarımız başlamıştır. Ürünlerimizi web sitemizden, çağrı merkezimizden ve ReklamoTV logosunu taşıyan tüm is ortaklarımızdan talep edebilirsiniz.

Müşteri sadakatinin kazanılmasındaki en önemli faktörlerin kalite ve hedef kitleye doğru mecra ile ulaşma bilinciyle oluşturulan reklamlarımız, şirketimizin özgün ve sorumluluk sahibi takım arkadaşları tarafından gereken titizlikle hazırlanır. Aynı zamanda yapılan çalışmalarda satış öncesi ve sonrası müşteri memnuniyetinin sürekli ve güncel tutulması firma kültürümüzün temel prensiplerindendir.

ReklamoTV, tecrübeli çalışanları ve müşterilerinden aldığı güçle her zaman kaliteli hizmeti, yeni trendleri ve ürünleri sizlerle buluşturmayı hedefleyen, büyüyerek güçlenen bir firma olarak sizlere hizmet vermeye devam edecektir.