ReklamoTv.Web/ViewModels/NewsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace ReklamoTv.Web.ViewModels
{
    public class NewsViewModel
    {

        public int NewsId { get; set; }
        [DisplayName("Başlık")]
        public string NewsTitle { get; set; }
        [DisplayName("Açıklama")]
        public string Description { get; set; }
        [DisplayName("Eklenme Tarih")]
        public DateTime NewsTime { get; set; }
        [DisplayName(" Haber ekleme başlangıç tarihi")]
        public DateTime StartTime { get; set; }
        [DisplayName("Haber ekleme bitiş tarihi")]
        public DateTime ExpiryTime { get; set; }
        [DisplayName("Haber spotu")]
        public string NewsSpot { get; set; }

    }
}

ReklamoTv.Web/Controllers/NewsController.cs
using AutoMapper;
using ReklamoTv.Model;
using ReklamoTv.Service;
using ReklamoTv.Web.Models;
using ReklamoTv.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReklamoTv.Web.Controllers
{
    public class NewsController:Controller
    {
        private readonly INewsService newsService;

        public NewsController(INewsService newsService)
        {
            this.newsService = newsService;
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NewsFormViewModel newsForm)
        {
            if (ModelState.IsValid)
            {
                var news = Mapper.Map<NewsFormViewModel, News>(newsForm);

               newsService.CreateNews(news);
                newsService.SaveNews();
                return RedirectToAction("Index");
            }
            return View(newsForm);
        }
        public ActionResult AjaxHandler(jQueryDataTableParamModel param)
        {
            string sSearch = "";
            if (param.sSearch != null) sSearch = param.sSearch;
            var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);
            var sortDirection = Request["sSortDir_0"]; // asc or desc
            int iTotalRecords;
            int iTotalDisplayRecords;
            var displayedNewses = newsService.Search(sSearch, sortColumnIndex, sortDirection, param.iDisplayStart, param.iDisplayLength, out iTotalRecords, out iTotalDisplayRecords);

            var result = from n in displayedNewses
                         select new[] { n.NewsId.ToString(), n.NewsTitle,n.NewsTime.ToString(), string.Empty };
            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = iTotalRecords,
                iTotalDisplayRecords = iTotalDisplayRecords,
                aaData = result.ToList()
            },
                JsonRequestBehavior.AllowGet);

        }


        public ActionResult Edit( int? id)
        {
            if (id.HasValue)
            {
                var news = newsService.GetNews(id.Value);
                if (news != null)
                {
                    var newsViewModel = Mapper.Map<News, NewsViewModel>(news);
                    return View(newsViewModel);
                }

            }
            return HttpNotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NewsFormViewModel newsForm)
        {
            if (ModelState.IsValid)
            {
                var city = Mapper.Map<NewsFormViewModel, News>( newsForm);
                newsService.UpdateNews(city);
                newsService.SaveNews();
                return RedirectToAction("Index");
            }
            return View(newsService);
        }
        public ActionResult Delete(int ? id)
        {
            if (id.HasValue)
            {
                var news = newsService.GetNews(id.Value);
                if (news != null)
                {
                    newsService.DeleteNews(news);
                    newsService.SaveNews();
                    return RedirectToAction("Index");
                }

            }
            return HttpNotFound();
        }


    }
}

ReklamoTv.Web/Views/News/Create.cshtml
@model ReklamoTv.Web.ViewModels.NewsFormViewModel
@{
    ViewBag.Title = "Güncelle";
}

<link href="assest/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="assest/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<br />
<div class="page-bar">
    <ul class="page-breadcrumb">

        <li>
            <span>Güncelle</span>
        </li>
    </ul>

</div>
<br />
<div class="row">
    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <h1 class="page-title">
                    Haberler
                </h1>

            </div>
            <div class="row">
                <div class="col-md-12">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                </div>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="portlet-body form">
                    <form role="form">
                        <div class="form-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.NewsTitle)
                                @Html.EditorFor(model => model.NewsTitle, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus" } })
                                @Html.ValidationMessageFor(model => model.NewsTitle, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Description)
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.NewsSpot)
                                @Html.EditorFor(model => model.NewsSpot, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus" } })
                                @Html.ValidationMessageFor(model => model.NewsSpot, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.StartTime)
                                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus", @type = "date" } })
                                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ExpiryTime)
                                @Html.EditorFor(model => model.ExpiryTime, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus", @type = "date" } })
                                @Html.ValidationMessageFor(model => model.ExpiryTime, "", new { @class = "text-danger" })
                             
                            </div>
                        </div>                            
                        <div class="form-body">
                            <div class="form-group">
                                @Html.LabelFor(model => model.NewsTime)
                                @Html.EditorFor(model => model.NewsTime, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus",  @type = "date" } })
                                @Html.ValidationMessageFor(model => model.NewsTime, "", new { @class = "text-danger" })
                            </div>
                        </div>



                        <div class="form-actions">
                            <button type="submit" class="btn blue">Ekle</button>
                            <button type="button" class="btn default" onclick="window.location='@Url.Action("Index","News")';">İptal</button>
                        </div>
                    </form>
                </div>
            }
        </div>
    </div>

</div>
<!-- END SAMPLE FORM PORTLET-->
<!-- BEGIN SAMPLE FORM PORTLET-->
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReklamoTv.Web/Views/News/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

ReklamoTv.Web/Views/News/Edit.cshtml
@model ReklamoTv.Web.ViewModels.NewsViewModel
@{
    ViewBag.Title = "Düzenle";
}

<link href="assest/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="assest/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<br />
<div class="page-bar">


</div>
<br />
<div class="row">
    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light bordered" style=" width 442px;">
            <div class="portlet-title">
                <h1 class="page-title">Düzenle</h1>

            </div>
            <div class="row">
                <div class="col-md-12">

                </div>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="portlet-body form">
                    <form role="form">
                        <div class="form-group">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.NewsId)
                            <div class="form-body">
                                @Html.LabelFor(model => model.Description)
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">
                                @Html.LabelFor(model => model.NewsTitle)
                                @Html.EditorFor(model => model.NewsTitle, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus" } })
                                @Html.ValidationMessageFor(model => model.NewsTitle, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">
                                @Html.LabelFor(model => model.NewsSpot)
                                @Html.EditorFor(model => model.NewsSpot, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus" } })
                                @Html.ValidationMessageFor(model => model.NewsSpot, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">
                                @Html.LabelFor(model => model.StartTime)
                                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus", @type = "date" } })
                                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">
                                @Html.LabelFor(model => model.ExpiryTime)
                                @Html.EditorFor(model => model.ExpiryTime, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus", @type = "date" } })
                                @Html.ValidationMessageFor(model => model.ExpiryTime, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-body">
                                @Html.LabelFor(model => model.NewsTime)
                                @Html.EditorFor(model => model.NewsTime, new { htmlAttributes = new { @tabindex = "1", @class = "form-control spinner", autofocus = "autofocus", @type = "date" } })
                                @Html.ValidationMessageFor(model => model.NewsTime, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn blue">Kaydet</button>
                            <button type="button" class="btn default" onclick="window.location='@Url.Action("Index","News")';">İptal</button>
                        </div>
                    </form>
                </div>
            }
        </div>
    </div>

</div>
<!-- END SAMPLE FORM PORTLET-->
<!-- BEGIN SAMPLE FORM PORTLET-->
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReklamoTv.Web/Views/News/Index.cshtml
@{
    ViewBag.Title = "Haberler";
}
<link href="assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<br />
<div class="page-bar">

</div>
<br />
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <h1 class="page-title">
                    Haber
                </h1>
            </div>

            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="btn-group">
                                <a href="/News/Create" id="sample_editable_1_new" class=" btn sbold green">
                                    Yeni Haber
                                    <i class="fa fa-plus"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover table-checkable order-column" id="allNewsTable">
                    <thead>
                        <tr>
                            <th>
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input type="checkbox" class="group-checkable" data-set="#allNewsTable .checkboxes" />
                                    <span></span>
                                </label>
                            </th>

                            <th>Başlık</th>
                            <th>Ekleme Tarihi</th>
                            <th>Eylemler</th>
                          
                        </tr>
                    </thead>

                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>
@section footer {
    <script src="assets/global/scripts/datatable.js" type="text/javascript"></script>
    <script src="assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
    <script src="assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
    <script src="~/Scripts/pages/news-index.js"></script>
    <script>
        $(document).ready(function () {
            initTable1();
        });
    </script>
}